# Generated by Django 4.2.13 on 2024-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
