# Generated by Django 4.2.11 on 2024-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_userprofile_alter_cart_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='static/'),
        ),
    ]
