# Generated by Django 4.2.11 on 2024-05-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
