# Generated by Django 4.2.13 on 2024-05-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
