# Generated by Django 4.2.11 on 2024-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_items_on_sale_items_sold_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sold',
        ),
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_sale', 'On Sale'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
