# Generated by Django 4.2.11 on 2024-05-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_items_on_sale_remove_items_sold_items_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
