# Generated by Django 4.2.11 on 2024-05-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_profile_balance_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('20%', '20%'), ('50%', '50%'), ('30%', '30%')], default='available', max_length=20),
        ),
    ]
