# Generated by Django 4.2.11 on 2024-05-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_items_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='status',
            field=models.CharField(choices=[('off 20%', 'off 20%'), ('off 50%', 'off 50%'), ('off 30%', 'off 30%')], default='available', max_length=20),
        ),
    ]
