# Generated by Django 4.2.13 on 2024-05-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('televisions', 'Televisions'), ('shoes', 'Shoes'), ('cutleries', 'Cutleries'), ('electrical_appliances', 'Electrical Appliances'), ('clothes', 'Clothes'), ('housewares', 'Housewares')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
