# Generated by Django 4.2.13 on 2024-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('televisions', 'Televisions'), ('shoes', 'Shoes'), ('cutleries', 'Cutleries'), ('electrical_appliances', 'Electrical Appliances'), ('clothes', 'Clothes'), ('housewares', 'Housewares')], max_length=50, null=True),
        ),
    ]
