# Generated by Django 4.2.13 on 2024-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_delete_category_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('televisions', 'Televisions'), ('phones', 'Phones'), ('shoes', 'Shoes'), ('cutleries', 'Cutleries'), ('electrical_appliances', 'Electrical Appliances'), ('clothes', 'Clothes'), ('accessories', 'Accessories'), ('housewares', 'Housewares')], max_length=50, null=True),
        ),
    ]
